name: Daily Code Run

on:
  schedule:
    - cron: '* * * * *'

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 'latest'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure to have a requirements.txt file

    - name: Run script
      run: python main.py
